{% set name = "pacemaker-lite" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3ce4629ae179fa6bc19958d50fce9c69ff5a3b7263ae60838e81efd6fa37cb1b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8

test:
  imports:
    - pacemaker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brohrer/pacemaker
  summary: For controlling the duration of iteration loops
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
