{% set name = "pacemaker-lite" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pacemaker-lite-{{ version }}.tar.gz
  sha256: 158b8bfe910f5cea13a610a247751d409367e6118a3790c22f2c999ba728aa1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8

test:
  imports:
    - pacemaker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brohrer/pacemaker
  summary: For controlling the duration of iteration loops
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
